---
- name: Install Mysql prerequisite
  apt:
    name: python-mysqldb

- name: Install PHP requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-gd
    - libapache2-mod-php

- name: Get PHP version
  command: php --version
  register: php_version
  changed_when: false

- name: Set PHP version
  set_fact: php_version="{{ php_version.stdout_lines[0] | regex_replace('^PHP (\d\.\d).*$','\\1') }}"

- name: Enable PHP apache module
  apache2_module: name="php{{ php_version }}"

- name: Find out timezone
  slurp:
     src: /etc/timezone
  register: etc_timezone

- name: Timezone in php.ini
  lineinfile:
    path: '/etc/php/{{ php_version }}/apache2/php.ini'
    regexp: '^;?date.timezone ='
    line: 'date.timezone = "{{ etc_timezone["content"] | b64decode | regex_replace("\n") }}"'
  notify: restart apache2

- name: Install Icinga2 IDO modules on Debian family
  apt:
    name: icinga2-ido-mysql
    state: latest

- name: Create a IDO Database for Icinga2
  mysql_db:
    name: "{{ icinga2_db }}"
    state: present
  register: icinga_ido_db

- name: Create Icinga2 IDO Database User and configure Grants
  mysql_user:
    name: "{{ icinga2_db_user }}"
    password: "{{ icinga2_db_pass }}"
    state: present
    priv: "{{ icinga2_db }}.*:ALL"

- name: Import the IDO Schema on Icinga Web Database (only once)
  mysql_db:
    name: "{{ icinga2_db }}"
    state: import
    target: "{{ icinga2_web_mysql_schema_debian }}"
  when: icinga_ido_db.changed == true

- name: Configure Icinga2 Ido Mysql Feature
  template:
    src: ido-mysql.conf.j2
    dest: "{{ icinga2_ido_mysql_conf }}"
    backup: yes
    owner: nagios
    group: nagios
    mode: 0640

- name: Enable Icinga2 Ido Mysql Feature
  command: "icinga2 feature enable ido-mysql"
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2

- name: Install Icinga Web2 on Debian family
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ icinga2_web2_ui_deb }}"
  tags: icinga2-ansible-web2-ui-install

- name: Create a Web Database for Icinga2
  mysql_db:
    name: "{{ icinga2_web2_db }}"
    state: present
  register: icinga_web_db

- name: Create Icinga2 Web Database User and configure Grants
  mysql_user:
    name: "{{ icinga2_web2_db_user }}"
    password: "{{ icinga2_web2_db_pass }}"
    state: present
    priv: "{{ icinga2_web2_db }}.*:ALL"

- name: Import the Web Schema on Icinga Web Database (only once)
  mysql_db:
    name: "{{ icinga2_web2_db }}"
    state: import
    target: "{{ icinga2_web2_mysql_schema_debian }}"
  when: icinga_web_db.changed == true

- name: Create an sql file to insert icingaadmin in DB
  template:
    src: insert_icingaadmin.sql.j2
    dest: /tmp/insert_icingaadmin.sql
    mode: 0640

- name: Import sql to create the icingaadmin
  mysql_db:
    state: import
    name: "{{ icinga2_web2_db }}"
    target: /tmp/insert_icingaadmin.sql
  register: mysql_import_output
  failed_when:
    - mysql_import_output | failed
    # When adding this user again mysql detects a duplicate entry and fails
    # with this error. Since this is the result we expect, it's not an error.
    - "'ERROR 1062' not in mysql_import_output.msg"
  notify: restart icinga2

- name: Configure Icinga2 Ido Mysql Feature
  template:
    src: ido-mysql.conf.j2
    dest: "{{ icinga2_ido_mysql_conf }}"
    backup: yes
    owner: nagios
    group: nagios
    mode: 0640

- name: Restart HTTPD and Icinga2 to Apply the Configuration
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - apache2
    - icinga2

- name: Add user www-data to group icingaweb2
  user:
    name: www-data
    groups: icingaweb2

- name: Adjust Directory Owner and Group
  file:
    path: "/etc/icingaweb2/modules"
    owner: www-data
    group: icingaweb2
    mode: 0755
    state: directory
    recurse: yes

# Director database
- name: create icingaweb2 director database
  mysql_db:
    name: "{{ icinga2_director_db }}"
    state: present
  notify: restart icinga2
  register: icinga_dir_db

- name: create icingaweb2 director user
  mysql_user:
    name: "{{ icinga2_director_db_user }}"
    password: "{{ icinga2_director_db_pass }}"
    priv: "{{ icinga2_director_db }}.*:ALL,GRANT"
  notify: restart icinga2

#- name: Import the Director Schema on Icinga Director Database (only once)
#  mysql_db:
#    name: "{{ icinga2_director_db }}"
#    state: import
#    target: "{{ icinga2_director_mysql_schema_debian }}"
#  when: icinga_dir_db.changed == true

- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0760"
    owner: www-data
    group: icingaweb2
  with_items:
    - /etc/icingaweb2/modules/monitoring
    - /etc/icingaweb2/modules/director
    - /etc/icingaweb2/enabledModules
  notify:
    - restart icinga2

- name: Deploy icingaweb2 config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icingaweb2/{{ item }}"
    backup: yes
    owner: www-data
    group: icingaweb2
    mode: 0660
  with_items:
    - groups.ini
    - resources.ini
    - config.ini
    - authentication.ini
    - roles.ini
  notify:
    - restart icinga2

- name: Deploy icingaweb2 monitoring config files
  template:
    src: "modules/monitoring/{{ item }}.j2"
    dest: "/etc/icingaweb2/modules/monitoring/{{ item }}"
    backup: yes
    owner: www-data
    group: icingaweb2
    mode: 0660
  with_items:
    - config.ini
    - backends.ini
    - commandtransports.ini
  notify:
    - restart icinga2

- name: Install/update director (Configuation GUI)
  git:
    dest: /usr/share/icingaweb2/modules/director/
    repo: https://github.com/Icinga/icingaweb2-module-director.git

- name: Deploy director config files
  template:
    src: "modules/director/{{ item }}.j2"
    dest: "/etc/icingaweb2/modules/director/{{ item }}"
    backup: yes
    owner: www-data
    group: icingaweb2
    mode: 0660
  with_items:
    - config.ini
    - kickstart.ini
  notify:
    - restart icinga2

- name: Enable icingaweb2 modules
  file:
    dest: "/etc/icingaweb2/enabledModules/{{ item }}"
    src: "/usr/share/icingaweb2/modules/{{ item }}"
    state: link
    owner: www-data
    group: icingaweb2
  with_items:
    - doc
    - monitoring
    - director
  notify:
    - restart icinga2

#- name: Fix SELinux permissions for /etc/icingaweb2
#  file:
#    path: /etc/icingaweb2
#    setype: httpd_sys_rw_content_t
#    recurse: yes

- name: Allow apache to connect to the network (Director exec's curl from PHP for reasons unknown!)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Deploy icingaweb2 director schema
  command: /bin/icingacli director migration run

- name: Flush handlers (restart icinga2 if needed)
  meta: flush_handlers

- name: Deploy icingaweb2 director configuration
  command: /bin/icingacli director kickstart run
  notify:
    - restart icinga2
